SET NAMES utf8mb4;

UPDATE recipe SET image_url = CASE id
    WHEN 1 THEN '/images/recipes/pexels-recipe-01-chicken-broccoli-bowl.jpg'
    WHEN 2 THEN '/images/recipes/pexels-recipe-02-shrimp-tofu-vegetable-soup.jpg'
    WHEN 3 THEN '/images/recipes/pexels-recipe-03-tomato-egg-oatmeal.jpg'
    WHEN 4 THEN '/images/recipes/pexels-recipe-04-tuna-egg-salad-bowl.jpg'
    WHEN 5 THEN '/images/recipes/pexels-recipe-05-cod-asparagus-plate.jpg'
    WHEN 6 THEN '/images/recipes/pexels-recipe-06-egg-tofu-custard.jpg'
    WHEN 7 THEN '/images/recipes/pexels-recipe-07-tomato-scrambled-egg.jpg'
    WHEN 8 THEN '/images/recipes/pexels-recipe-08-beef-potato-carrot-stew.jpg'
    WHEN 9 THEN '/images/recipes/pexels-recipe-09-mushroom-tofu-rice.jpg'
    WHEN 10 THEN '/images/recipes/pexels-recipe-10-salmon-poke-quinoa-bowl.jpg'
    WHEN 11 THEN '/images/recipes/pexels-recipe-11-kungpao-chicken-light.jpg'
    WHEN 12 THEN '/images/recipes/pexels-recipe-12-seaweed-egg-noodle-soup.jpg'
    WHEN 13 THEN '/images/recipes/pexels-recipe-13-bulgogi-beef-rice-bowl.jpg'
    WHEN 14 THEN '/images/recipes/pexels-recipe-14-chicken-avocado-wrap.jpg'
    WHEN 15 THEN '/images/recipes/pexels-recipe-15-beef-egg-quinoa-bowl.jpg'
    WHEN 16 THEN '/images/recipes/pexels-recipe-16-tofu-broccoli-protein-bowl.jpg'
    WHEN 17 THEN '/images/recipes/pexels-recipe-17-tuna-corn-sandwich.jpg'
    WHEN 18 THEN '/images/recipes/pexels-recipe-18-shrimp-egg-pasta.jpg'
    WHEN 19 THEN '/images/recipes/pexels-recipe-19-shrimp-winter-melon-soup.jpg'
    WHEN 20 THEN '/images/recipes/pexels-recipe-20-spinach-egg-tofu-soup.jpg'
    WHEN 21 THEN '/images/recipes/pexels-recipe-21-fish-broccoli-plate.jpg'
    WHEN 22 THEN '/images/recipes/pexels-recipe-22-chicken-salad-bowl.jpg'
    WHEN 23 THEN '/images/recipes/pexels-recipe-23-tomato-tofu-mushroom-soup.jpg'
    WHEN 24 THEN '/images/recipes/pexels-recipe-24-zucchini-chicken-egg.jpg'
    WHEN 25 THEN '/images/recipes/pexels-recipe-25-sweet-potato-yogurt-bowl.jpg'
    WHEN 26 THEN '/images/recipes/pexels-recipe-26-cucumber-shrimp-egg-cup.jpg'
    WHEN 27 THEN '/images/recipes/pexels-recipe-27-cabbage-tofu-chicken-soup.jpg'
    WHEN 28 THEN '/images/recipes/pexels-recipe-28-bibimbap-beef-rice-bowl.jpg'
    WHEN 29 THEN '/images/recipes/pexels-recipe-29-mushroom-chicken-grain-rice.jpg'
    WHEN 30 THEN '/images/recipes/pexels-recipe-30-tomato-beef-soba-noodle.jpg'
    WHEN 31 THEN '/images/recipes/pexels-recipe-31-pumpkin-egg-porridge.jpg'
    WHEN 32 THEN '/images/recipes/pexels-recipe-32-tomato-tofu-beef-stew.jpg'
    WHEN 33 THEN '/images/recipes/pexels-recipe-33-pork-cabbage-fried-rice.jpg'
    WHEN 34 THEN '/images/recipes/pexels-recipe-34-mushroom-greens-egg-noodle.jpg'
    WHEN 35 THEN '/images/recipes/pexels-recipe-35-chicken-kale-rice-bowl.jpg'
    WHEN 36 THEN '/images/recipes/pexels-recipe-36-corn-egg-milk-oatmeal.jpg'
    WHEN 37 THEN '/images/recipes/pexels-recipe-37-buddha-sweet-potato-bowl.jpg'
    WHEN 38 THEN '/images/recipes/pexels-recipe-38-chicken-thigh-grain-rice.jpg'
    WHEN 39 THEN '/images/recipes/pexels-recipe-39-shrimp-avocado-salad.jpg'
    WHEN 40 THEN '/images/recipes/pexels-recipe-40-pork-egg-protein-plate.jpg'
    WHEN 41 THEN '/images/recipes/pexels-recipe-41-quinoa-chicken-bowl.jpg'
    WHEN 42 THEN '/images/recipes/pexels-recipe-42-chicken-yogurt-wrap.jpg'
    WHEN 43 THEN '/images/recipes/pexels-recipe-43-fish-sweet-potato-plate.jpg'
    WHEN 44 THEN '/images/recipes/pexels-recipe-44-beef-double-egg-rice.jpg'
    WHEN 45 THEN '/images/recipes/pexels-recipe-45-shrimp-poke-bowl.jpg'
    ELSE image_url
END
WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45);
